name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 116.203.213.63
        username: root
        key: ${{ secrets.server }}
        script: |
          # Navigate to the project directory on the server
          cd /var/www/Duarte/Sign-Language-Reader-Frontend
          # Pull the latest changes from the GitHub repository
          git pull origin main
          # Remove the old dist folder if it exists
          rm -rf dist
          # Install dependencies
          npm install
          # Run the build
          npm run build

    - name: Restart Nginx
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 116.203.213.63
        username: root
        key: ${{ secrets.server }}
        script: |
          sudo systemctl restart nginx
